spring.application.name=currencies-api

spring.datasource.url=jdbc:postgresql://localhost:5432/cotacoes
spring.datasource.username=cotacoes
spring.datasource.password=cotacoes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true